spring.application.name=resume-analyzer
server.port=${SERVER_PORT}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ========== DATABASE CONFIG ==========
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ========== GEMINI CONFIG ==========
spring.ai.vertex.ai.gemini.project-id=${SPRING_AI_PROJECT_ID}
spring.ai.vertex.ai.gemini.location=${SPRING_AI_LOCATION}
spring.ai.vertex.ai.gemini.model=${SPRING_AI_MODEL}
spring.ai.vertex.ai.gemini.credentials.location=${GOOGLE_APPLICATION_CREDENTIALS}

# ========== JWT CONFIG ==========
jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
