spring.application.name=resume-analyzer
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ========== DATABASE CONFIG ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/est
spring.datasource.username=postgres
spring.datasource.password=00000000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ========== GEMINI CONFIG (Spring AI) ==========
spring.ai.vertex.ai.gemini.project-id=resumeanalyzer-476905
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.model=gemini-1.5-pro
spring.ai.vertex.ai.gemini.credentials.location=${GOOGLE_APPLICATION_CREDENTIALS}

jwt.secret=aReallyStrongSecretKeyThatIsAtLeast32BytesLong123!
jwt.access.expiration=3600000
jwt.refresh.expiration=604800000
